name: quickly_indian
description: A smart South Indian food delivery app

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  provider: ^6.0.5
  firebase_core: ^2.27.0
  firebase_auth: ^4.20.0 # Compatible with firebase_core v2
  cloud_firestore: ^4.17.0
  google_sign_in: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_qi.png
